# Generated by Django 6.0.1 on 2026-02-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_typing_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='main_conver_last_me_04db79_idx',
            old_name='main_conve_last_me_b0e74b_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='main_messag_convers_05de84_idx',
            old_name='main_messa_convers_8aaf0b_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='main_messag_recipie_e66beb_idx',
            old_name='main_messa_recipie_29c2ab_idx',
        ),
        migrations.RenameIndex(
            model_name='typingstatus',
            new_name='main_typing_convers_0d9fc9_idx',
            old_name='main_typin_convers_4b58c0_idx',
        ),
    ]
