# Generated by Django 6.0.1 on 2026-02-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wall_posts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallcomment',
            new_name='main_wallco_post_id_7425d7_idx',
            old_name='main_wallco_post_id_4b5e29_idx',
        ),
        migrations.RenameIndex(
            model_name='wallcomment',
            new_name='main_wallco_author__545374_idx',
            old_name='main_wallco_author__1c57b3_idx',
        ),
        migrations.RenameIndex(
            model_name='wallpost',
            new_name='main_wallpo_owner_i_a8ae7b_idx',
            old_name='main_wallpo_owner_i_f52aa0_idx',
        ),
        migrations.RenameIndex(
            model_name='wallpost',
            new_name='main_wallpo_author__ee924e_idx',
            old_name='main_wallpo_author__113f61_idx',
        ),
    ]
